import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';
import type { paths } from './v1'; // generated by openapi-typescript

export const client = createFetchClient<paths>({
  baseUrl: 'http://localhost:8080/v1/',
});
export const $api = createClient(client);
